# docker compose up --build --no-log-prefix
services:
  run-function-calling:
    build: .
    environment:
      - MODEL_RUNNER_BASE_URL=${MODEL_RUNNER_BASE_URL}
      - MODEL_RUNNER_TOOL_LLM=${MODEL_RUNNER_TOOL_LLM}
      - MODEL_RUNNER_CHAT_LLM=${MODEL_RUNNER_CHAT_LLM}
    depends_on:
      - download-tool-model
      - download-chat-model


  download-tool-model:
    provider:
      type: model
      options:
        model: ${MODEL_RUNNER_TOOL_LLM}

  download-chat-model:
    provider:
      type: model
      options:
        model: ${MODEL_RUNNER_CHAT_LLM}
